Repository falcosecurity/dbg-go, pull requests merged in 2023-10, with the labels that each got.

#29 docs: add license headers and spdx id
  cmd/build/build_configs.go
  cmd/cleanup/cleanup_configs.go
  cmd/cleanup/cleanup_drivers.go
  cmd/configs.go
  cmd/drivers.go
  cmd/generate/generate_configs.go
  cmd/publish/publish_drivers.go
  cmd/root.go
  cmd/stats/stats_configs.go
  cmd/stats/stats_drivers.go
  cmd/validate/validate_configs.go
  main.go
  pkg/build/build.go
  pkg/build/build_test.go
  pkg/build/types.go
  pkg/cleanup/cleaner_file.go
  pkg/cleanup/cleaner_s3.go
  pkg/cleanup/cleanup.go
  pkg/cleanup/cleanup_test.go
  pkg/cleanup/types.go
  pkg/generate/constants.go
  pkg/generate/errors.go
  pkg/generate/generate.go
  pkg/generate/generate_test.go
  pkg/generate/types.go
  pkg/generate/utils.go
  pkg/publish/publish.go
  pkg/publish/publish_test.go
  pkg/publish/types.go
  pkg/root/constants.go
  pkg/root/distro.go
  pkg/root/types.go
  pkg/root/utils.go
  pkg/stats/stats.go
  pkg/stats/stats_test.go
  pkg/stats/statter_file.go
  pkg/stats/statter_s3.go
  pkg/stats/types.go
  pkg/utils/s3/s3utils.go
  pkg/utils/s3/types.go
  pkg/utils/test/test.go
  pkg/validate/errors.go
  pkg/validate/types.go
  pkg/validate/validate.go
  pkg/validate/validate_test.go
Labels: dco-signoff: yes, approved, needs-kind, lgtm, size/XXL

#32 fix(pkg/build): ensure output folders exist.
  pkg/build/build.go
  pkg/build/build_test.go
Labels: dco-signoff: yes, approved, needs-kind, size/XS, lgtm

#33 chore(pkg/root): enable support for PhotonOS.
  pkg/root/distro.go
Labels: dco-signoff: yes, approved, needs-kind, size/XS, lgtm

#35 update: bumped driverkit to v0.15.3.
  Makefile
  go.mod
  go.sum
Labels: dco-signoff: yes, approved, needs-kind, size/XS, lgtm

#36 cleanup(pkg): dropped kernel crawler distro type.
  pkg/generate/generate.go
  pkg/root/distro.go
Labels: dco-signoff: yes, approved, needs-kind, lgtm, size/M
